forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/apt'
mod 'puppetlabs/ntp'
mod 'attachmentgenie/locales'
mod 'example42/timezone'
mod 'example42/logrotate'